### PR TITLE
Workaround for file paths that have Unicode characters breaking SoX

### LINKED ISSUE #200: SoX is unable to deal with unicode characters in the path of a filename
## Describe the bug
Sometimes, audio files have unicode characters in their paths. In these cases SoX fails to process the file.

## Expected behavior 
We should be able to process any file that has any valid file path.

## Diagnostics

- I Confirm I have followed [the instructions for reporting a bug](https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/bug_report.md)
- I have attached a log:  [log_20181023T033126Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/2504378/log_20181023T033126Z.txt)
- I have answered the following questions:
    
  - **Operating system:**  Windows 10 Version 1803
    
  - **AP.exe version:** 76e3b8ae11e43cdda7e553e43040ef59a8253a0e
    
  - **The data used can be found:** `Y:\WesternGhatsCentralIndia\201809\SAT_MANG_3\Recordings\REC_C_001\REC_C_2018-06-16\REC_C_20180616_145526.wav`
  - **The command I used:** (see log file)
  - **The config file I used:**  https://github.com/QutEcoacoustics/audio-analysis/blob/76e3b8ae11e43cdda7e553e43040ef59a8253a0e/src/AnalysisConfigFiles/Towsey.Acoustic.yml

## Additional Details

`sox --info Y:\WesternGhatsCentralIndia\201809\SAT_MANG_3\Recordings\REC_C_001\REC_C_2018-06-16\REC_C_20180616_145526.wav` also fails indicating that this is an upstream problem with SoX.

These unicode chracers seem to be inserted occasionally by something. We've run into them before in filenames. I suspect something on a MacOS operating system is inserting them. The character, U+F021 is located in the [_Private Use Area_](https://codepoints.net/U+F021?lang=en) and has no actual representation... whether this is the literal character that was encoded in the filenames or the result of some windows/unix normalization is unclear.

### PR DESCRIPTION
**Pull request by atruskie**
Fixes #200 

@peichins - can I get you to test the attached artefact on a Max. Make sure you test on a file that has some Unicode character somewhere in its path. Ideally, nothing has changed on MacOS.

P.S. Hi from Singapore  👋

### CODE REVIEW

**Comment by atruskie** [comment]
@mkholghi and @peichins: *nudge*

**Comment by peichins** [comment]
Have tested this on mac using audio2csv with TowseyAcoustic.yml, where the source file had unicode character (copied from the description in the issue) in the directory
`/Users/eichinsp/Desktop/temp/ap_test/in/dir_with_unicode__/REC_C_20180616_185529.wav`
This appeared to work without any problem. 
Also tested with the same directory, but with unicode in the file name
`/Users/eichinsp/Desktop/temp/ap_test/in/dir_with_unicode__/REC_C_20180616_185529🤷‍♂️🤷‍♂️_1_1.wav`
(this character was copied from the test code)

This failed. Only some of the files (none of the csvs) were written to the output directory. 

Verbose logging attached here (minus the first part due to the length)
[verbose_log.txt](https://github.com/QutEcoacoustics/audio-analysis/files/2537451/verbose_log.txt)

**Comment by atruskie** [comment]
Thanks for testing @peichins though you've only included a log fragment which is not so useful: See https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/logs.md for getting the full log file.

But I have a hunch for what the bug is: can you place the source and destination files in short directory paths?

e.g. 
`/temp/dir_/REC_C_20180616_185529🤷‍♂️🤷‍♂️_1_1.wav` and 
`/temp/results` for input source file and output directory respectively.

**Comment by peichins** [comment]
I have tried running it again with shorter paths: 
`/temp/in/dir_/REC_C_20180616_185529🤷‍♂️🤷‍♂️_1_1.wav` to `/temp/out/`
This *failed*, here is the log:
[log_20181102T012216Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/2540728/log_20181102T012216Z.txt)

However, I tried it with different characters in the filename, and it worked
`/temp/in/dir_/REC_C_20180616_185529_1_1.wav` to `/temp/out/``
This *worked*, here is the log: 
[log_20181102T013828Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/2540744/log_20181102T013828Z.txt)

And I tried the following (only one of that character):
`/temp/in/dir_/REC_C_20180616_185529🤷‍♂️_1_1.wav` 
This *failed*, here is the log:
[log_20181102T014439Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/2540747/log_20181102T014439Z.txt)

**Pull request merged**
